version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:latest # The primary container where steps are run

    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            mysql --version
            pwd
            ls -la
            mysql -u root -p --execute="SELECT * FROM test_db.Persons"
