version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:latest
    environment:
      DB_ROOT_USER: root
      DB_URL: jdbc:mysql://localhost:3306/testdb
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_PASS: ""
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ''
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: Wait for Database Connection
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      #install mysql client
      - run: sudo apt-get install mysql-client
      # create databases
      - run: mysql -h 127.0.0.1 -u root -e "create database carddb"
      - run: mysql -h 127.0.0.1 -u root -e "create database cardholderdb"
      - run: mysql -h 127.0.0.1 -u root -e "create database memberdb"