version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:8.0.4
      # - image: circleci/mysql:latest # The primary container where steps are run
    environment:
      DB_HOST: 127.0.0.1
      command: [--default-authentication-plugin=mysql_native_password]
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: app_test
        MYSQL_USER: root
    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            # sudo apt-get install default-mysql-client
            # mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
            mysql --version
            pwd
            ls -la
            mysql -u root -p --execute="SELECT * FROM test_db.Persons"
