version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: mysql

    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            mysql --version
            pwd
            ls -la
            mysql -u root -p'rootpw'
