version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:latest # The primary container where steps are run

    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            # sudo apt-get install default-mysql-client
            # mysql -h 127.0.0.1 -u user -ppassw0rd test_db < sql-data/dummy.sql
            mysql --version
            pwd
            ls -la
            mysql -u root -p --execute="SELECT * FROM test_db.Persons"
